const CASHBACK_STORE_SIZE = 6;

const CASHBACK_INFO_TAB_VIEW_SIZE = 1;

const CASHBACK_INFO_TAB_INCREMENT_SIZE = 3;

export {
    CASHBACK_STORE_SIZE, CASHBACK_INFO_TAB_VIEW_SIZE, CASHBACK_INFO_TAB_INCREMENT_SIZE
};
